### ISSUE TITLE
Share trip progress

### ISSUE THREAD

**Issue by acarlo79** [costastf/locationsharinglib#48]
Hello,
there is a new functionality in google maps to share the trip progress. This is quite useful since provide also an ETA.
Could you get this new value for the ETA? It woul be nice to use it to update the NEST thermostat with the ETA to home.

Thanks!

**Comment by costastf** [comment]
Hi, I will look into this after next week, currently in a trip. Thanks for reporting!

**Comment by costastf** [comment]
Hi @acarlo79. Apologies for the long time to reply. Can you please provide some more details about that feature? I do not seem to be able to find it. Do you mean google maps as in the android app? If that is the case I am afraid that that does not work since this code leverages the web version and if the feature is not there it is not possible for me to implement. If it is can you please provide a detailed explanation of what it is and how do you think it can be implemented?

**Comment by costastf** [comment]
Closing now due to lack of information but if this is valid feel free to reopen.
