### ISSUE TITLE
maps-cookie-getter login blocked

### ISSUE THREAD

**Issue by oweijers** [costastf/locationsharinglib#69]
It looks like google implemented some update in the past few days, which blocks logging into an account with any browser in automated test mode.

maps-cookie-getter opens a browser, but after logging in, the following error pops up:

[Error](https://i.stack.imgur.com/u5p4j.png)

"You are trying to sign in from a browser or app that doesn't allow us to keep your account secure."

**Comment by costastf** [comment]
</sigh> Not much we can do I guess. That renders the cookie getter project useless. I guess it is locale based so it will propably keep working for some people. As part of closing #66 I will try to implement a text version of the cookies on the library so they can be retrieved by an extension of the browser. Closing this since it is the wrong place for it anyway. Thanks for reporting.
