### ISSUE TITLE
Not getting shared persons location updates

### ISSUE THREAD

**Issue by elad-bar** [costastf/locationsharinglib#73]
Hi,

Since v98 of HA (v4.1.0 of locationsharinglib) with the new cookie I stopped getting updates about regarding shared persons from get_all_people (just getting the logged-in user),
when running the package directly from python i'm getting same results,
Can you please assist?

thanks

**Comment by elad-bar** [comment]
I used the solution suggested for issue #71 , 
To run Hass.io as well as other linux based services, I'm using docker over ubuntu server,
My workstation is running Windows 10, so I ran docker of ubuntu desktop to check it.

Seems that the issue is when extracting in Windows the cookies,
Is the something you can do to allow reading cookies of Chrome within Windows 10?

thanks

**Comment by costastf** [comment]
Hi @elad-bar , sadly this is not something that I "allow" or "disallow". Apparently the cookies that you get with a windows 10 machine are not fully usable. Could be that google is matching something in the cookies with the browser, although I doubt that since my Mac created cookie works just fine on my ubuntu machine. I am afraid there is not much I can do since the cookies are provided by the service and the addon (hopefully) extracts all of them. If I had to guess I would guess that the addon that you use on Windows to extract the cookies does not behave like on the other operating systems. If you feel like troubleshooting diff the two cookies and see what is not there on the windows one.
